### ISSUE TITLE
Crashes in Mobile Safari (iOS)

### ISSUE THREAD

**Issue by whbassignani** [robinwhittleton/design-critique-cards#11]
Whole site crashes on-load on iOS. Loads twice, and then crashes all the way. Error text shown: "A problem repeatedly occurred"

https://whatismybrowser.com/w/WRTPT9M

Occurred both with and without my content blocker turned on.

**Comment by robinwhittleton** [comment]
Thanks for the report. I’m going to investigate this and work out what’s going on.

**Comment by robinwhittleton** [comment]
I’ve removed the ”attract mode” opening card wiggle. I’m not sure why this was crashing Safari, and I couldn’t find any magic combo to get it to work. Hopefully Apple will fix this and I can reinstate it in the future.
